fix: Failed to compile on Linux with libed247_static.a, replace with libed247.so Compilation issues with libed247_static.a: - Requires libxml2.a -  undefined reference to `std::__throw_bad_array_new_length()'